### ISSUE TITLE
fake-bootstrap snippet should escape certain characters

### ISSUE THREAD

**Issue by kurtschelfthout** [ionide/ionide-fake#4]
let run cmd args dir =
        let pinfo = ProcessStartInfo(cmd,args)
        pinfo.WorkingDirectory <- dir; pinfo.UseShellExecute <- false; pinfo.RedirectStandardOutput <- true
        let proc = Process.Start(pinfo)
        proc.StandardOutput.ReadToEnd() |> printfn "< %s >
    %s" cmd; proc.WaitForExit()

    run @".paketpaket.bootstrapper.exe" "" ""
    run @".paketpaket.exe" "restore -f" ""

Notice the inadvertent linebreak after `>` in the last line of `run`, as well as no backslashes in the two path arguments to `run`.

**Comment by cloudRoutine** [comment]
looks like backslashes are escaped `\\\\` in the snippets
will be fixed in the next release https://github.com/ionide/ionide-fake/pull/5
